name: Blaze Bench

on:
  push:
  workflow_dispatch:

jobs:
  bench-blaze:
    runs-on: leica
    steps:
      - uses: actions/checkout@v4

      - name: Env info
        run: |
          echo "labels=$RUNNER_LABELS" | tee bench-env-blaze.txt
          nproc | xargs -I{} echo "nproc={}" | tee -a bench-env-blaze.txt
          uname -a | tee -a bench-env-blaze.txt
          lscpu || true

      - name: CPU bench (sysbench, 60s)
        run: |
          docker run --rm --cpuset-cpus=0-$(($(nproc)-1)) ubuntu:22.04 bash -lc '
            set -e
            apt-get update -qq
            apt-get install -y -qq sysbench > /dev/null
            sysbench cpu --threads=$(nproc) --time=60 run
          ' | tee bench-sysbench-blaze.txt

      - name: Crypto bench (OpenSSL)
        run: |
          docker run --rm ubuntu:22.04 bash -lc '
            set -e
            apt-get update -qq
            apt-get install -y -qq openssl > /dev/null
            openssl version
            openssl speed -multi $(nproc) sha256 sha512 aes-256-cbc rsa2048
          ' | tee bench-openssl-blaze.txt

      - name: Compression bench (zstd 2GB)
        run: |
          docker run --rm -v "$PWD:/w" -w /w ubuntu:22.04 bash -lc '
            set -e
            apt-get update -qq
            apt-get install -y -qq zstd > /dev/null
            dd if=/dev/zero of=blob.bin bs=1M count=2048 status=none
            /usr/bin/time -f "elapsed=%E cpu=%P" zstd -T0 -19 blob.bin -o blob.bin.zst
            ls -lh blob.bin*
          ' | tee bench-zstd-blaze.txt

      - name: Upload results (Blaze)
        uses: actions/upload-artifact@v4
        with:
          name: results-blaze
          path: |
            bench-*-blaze.txt